version: "3.9"

services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - psql-app

  psql-app:
    image: postgres:14.5
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
    volumes:
      - pgdata-project2:/var/lib/postgresql/data/pgdata

volumes:
  pgdata-project2:
